<a href="https://colab.research.google.com/github/Khushmit-sonar/essestial_math_forAIML_python/blob/main/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#Define 3*2 matrices
p = np.array([[1,2],[2,3],[3,4]])
print(p)

[[1 2]
 [2 3]
 [3 4]]


In [7]:
q = np.array([[1,-1],[2,5],[-2,3]])
print(q)

[[ 1 -1]
 [ 2  5]
 [-2  3]]


In [6]:
#Adding two matrices
c1 = np.add(p,q)
print(c1)

[[2 1]
 [4 8]
 [1 7]]


In [10]:
#substraction of two matrices
c2 = np.subtract(p,q)
print(c2)

[[ 0  3]
 [ 0 -2]
 [ 5  1]]


In [11]:
#multiplication of two matrices
#for multiplication we neew 3*2 and 2 * 3 matrices

r = np.array([[1,2,3],[1,3,2]])
print(r)

[[1 2 3]
 [1 3 2]]


In [13]:
#multiplication of q and r matrices

c3 = np.dot(q,r)
print(c3)

[[ 0 -1  1]
 [ 7 19 16]
 [ 1  5  0]]


In [14]:
#inverser of m matrices
m = np.array([[1,-1],[2,3]])
print(np.linalg.inv(m))

[[ 0.6  0.2]
 [-0.4  0.2]]
