<a href="https://colab.research.google.com/github/Khushmit-sonar/essestial_math_forAIML_python/blob/main/vector1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [ ]:
#addition and substrtion of vectors
print(v+w)
print(v-w)

[3 4 4]
[-1 -6  0]


In [ ]:
#scaler multiplication of vectors
print(3*w)

[ 6 15  6]


In [ ]:
#find the length of vector
print(np.linalg.norm(v))

2.449489742783178


In [ ]:
#dot product of vectors
s=np.dot(v,w)
print(s)

1
